# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

#Default language
en:
  languageCode: en-us
  #Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

#Uncomment the lines below to configure your website in a second language.
de:
  languageCode: de
  contentDir: content/de
  title: Sebastian Siuda
  params:
    description: Psychologisches Coaching & Beratung von Dr. Sebastian Siuda - systemische Methoden, wissenschaftlich fundiert, individuell auf Ihre Ziele abgestimmt.
  menu:
    main:
      - name: "Über mich"
        url: /
        weight: 10
      - name: Forschung
        url: /#forschung
        weight: 11
      - name: Lehre
        url: teaching/
        weight: 40
      - name: Coaching
        url: coaching/
        weight: 50   