# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'ProfessionalService'
    org_name: 'Sebastian Siuda Psychologie & Coaching'
    description: 'Psychological coaching & consulting by Dr. Sebastian Siuda - systemically grounded, evidence-based, tailored to your goals.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: ""

# Site footer
footer:
  copyright:
    notice: '© {year} Sebastian Siuda | <a href="/impressum/">Impressum</a> | <a href="/datenschutz/">Datenschutz</a>'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false


# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
